services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true

  AmzsCMS\BlockBundle\:
    resource: '../../../src/'
    exclude:
      - '../../DependencyInjection/'
      - '../../Kernel.php'
      - '../../Enum/'
      - '../../Traits/'
      - '../../AmzsBlockBundle.php'

  AmzsCMS\BlockBundle\Routing\AmzsBlockLoader:
    tags: [ routing.loader ]

